### ISSUE TITLE
potential memory leak?

### ISSUE THREAD

**Issue by jayarjo** [apieceofbart/debounce-promise-with-cancel#3]
Why do you create new Promise for every call, doesn't it pollute memory or something? Why not create promise once and simply resolve it when timer goes out?

**Comment by apieceofbart** [comment]
hi @jayarjo
It's been a while when I last looked at that code but I am not sure I understand your problem - in your code you would call `debounce` once and that will give a single Promise. Is there a reason you call `debounce` multiple times?
Maybe you could provide an example so we could check if there's a memory leak?

**Comment by apieceofbart** [comment]
@jayarjo I am going to close the ticket since there was no answer from you - feel free to reopen if you want to add something
